// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow for randomly selecting an affirmation.
 *
 * - selectAffirmation - A function that handles the random selection of an affirmation.
 * - SelectAffirmationOutput - The return type for the selectAffirmation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SelectAffirmationOutputSchema = z.object({
  affirmation: z.string().describe('A randomly selected affirmation.'),
});

export type SelectAffirmationOutput = z.infer<typeof SelectAffirmationOutputSchema>;

const affirmations = [
  'Sí, definitivamente',
  'Es cierto',
  'Es decididamente así',
  'Sin lugar a dudas',
  'Puedes confiar en ello',
  'Como yo lo veo, sí',
  'Lo más probable',
  'Perspectiva buena',
  'Sí',
  'Las señales apuntan a que sí',
];

export async function selectAffirmation(): Promise<SelectAffirmationOutput> {
  return selectAffirmationFlow();
}

const selectAffirmationFlow = ai.defineFlow({
    name: 'selectAffirmationFlow',
    outputSchema: SelectAffirmationOutputSchema,
  },
  async () => {
    const randomIndex = Math.floor(Math.random() * affirmations.length);
    const affirmation = affirmations[randomIndex];
    return {affirmation};
  }
);
